identifier-prefix: pangaea.terranexus.dggs.api

imports:
  - default
  - https://ogcincubator.github.io/bblock-prov-schema/build/register.json
#  - https://geofizzydrink.github.io/test_bblock/build/register.json
