"$schema": https://json-schema.org/draft/2020-12/schema
description: CWL Provenance Chain for DGGS actions
allOf:
  - $ref: bblocks://ogc.ogc-utils.prov#/$defs/Entity
  - $ref: bblocks://ogc.geo.json-fg.featureCollection

