"$schema": https://json-schema.org/draft/2020-12/schema
description: CWL Provenance Chain for DGGS actions
allOf: 
    - $ref: bblocks://ogc.ogc-utils.prov#/$defs/Entity
    - $ref: bblocks://ogc.geo.features.featureCollection
    - type: object
    - properties:
        a:
          type: string
          format: uri
        b:
          type: number

